version: 1.0
released: 2018-07-18

# openweathermap parameters
openweathermap:
    url: http://api.openweathermap.org/data/2.5/
    wheater: weather?
    forecast: forecast?
    units: units=metric
    appid: appid=

#telegram api
telegram:
  api:
  name:

#mongo connection
mongo:
  uri: mongodb://localhost:27017
  database: weatherTelegramBot
  userCollection: users


