version: 1.0
released: 2018-07-18

# openweathermap parameters
openweathermap:
    url: http://api.openweathermap.org/data/2.5/
    wheater: weather?q=
    forecast: forecast?
    units: units=metric
    appid: appid=96508ef365164a7643f9a49fb8c5b0bd

